name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build theme assets (SCSS & JS)
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy using Rsync
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > key.pem
        chmod 600 key.pem
        rsync -avz --exclude '.git' -e "ssh -i key.pem" . ${REMOTE_USER}@${REMOTE_SERVER}:${REMOTE_PATH}

    - name: Clean up SSH key
      run: rm -f key.pem
